src/Entity/Stock.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StockRepository")
 */
class Stock
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $chasuble;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $ballon;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $plot;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $barre;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $mini_plot;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $maillot;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $short;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $sifflet;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getChasuble(): ?int
    {
        return $this->chasuble;
    }

    public function setChasuble(?int $chasuble): self
    {
        $this->chasuble = $chasuble;

        return $this;
    }

    public function getBallon(): ?int
    {
        return $this->ballon;
    }

    public function setBallon(?int $ballon): self
    {
        $this->ballon = $ballon;

        return $this;
    }

    public function getPlot(): ?int
    {
        return $this->plot;
    }

    public function setPlot(?int $plot): self
    {
        $this->plot = $plot;

        return $this;
    }

    public function getBarre(): ?int
    {
        return $this->barre;
    }

    public function setBarre(?int $barre): self
    {
        $this->barre = $barre;

        return $this;
    }

    public function getMiniPlot(): ?int
    {
        return $this->mini_plot;
    }

    public function setMiniPlot(?int $mini_plot): self
    {
        $this->mini_plot = $mini_plot;

        return $this;
    }

    public function getMaillot(): ?int
    {
        return $this->maillot;
    }

    public function setMaillot(?int $maillot): self
    {
        $this->maillot = $maillot;

        return $this;
    }

    public function getShort(): ?int
    {
        return $this->short;
    }

    public function setShort(?int $short): self
    {
        $this->short = $short;

        return $this;
    }

    public function getSifflet(): ?int
    {
        return $this->sifflet;
    }

    public function setSifflet(?int $sifflet): self
    {
        $this->sifflet = $sifflet;

        return $this;
    }
}

src/Form/StockType.php
<?php

namespace App\Form;

use App\Entity\Stock;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StockType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('chasuble')
            ->add('ballon')
            ->add('plot')
            ->add('barre')
            ->add('mini_plot')
            ->add('maillot')
            ->add('short')
            ->add('sifflet')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Stock::class,
        ]);
    }
}

src/Controller/IndexController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class IndexController extends AbstractController
{
    /**
     * @Route("/", name="accueil")
     */
    public function accueil()
    {
        return $this->render('index/accueil.html.twig', [
            'controller_name' => 'IndexController',
        ]);
    }
}

src/Controller/StockController.php
<?php

namespace App\Controller;

use App\Entity\Stock;
use App\Form\StockType;
use App\Repository\StockRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class StockController extends AbstractController
{
    /**
     * @Route("/info", name="information", methods={"GET"})
     */
    public function information(StockRepository $stockRepository)
    {
        return $this->render('info/information.html.twig', [
            'stocks' => $stockRepository->findAll(),
        ]);
    }

    /**
     * @Route("/stock", name="stockage", methods={"GET"})
     */
    public function stockage(StockRepository $stockRepository): Response
    {
        return $this->render('stock/stockage.html.twig', [
            'stocks' => $stockRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="nouveau", methods={"GET","POST"})
     */
    public function nouveau(Request $request): Response
    {
        $stock = new Stock();
        $form = $this->createForm(StockType::class, $stock);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($stock);
            $entityManager->flush();

            return $this->redirectToRoute('stockage');
        }

        return $this->render('stock/nouveau.html.twig', [
            'stock' => $stock,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="afficher", methods={"GET"})
     */
    public function afficher(Stock $stock): Response
    {
        return $this->render('stock/afficher.html.twig', [
            'stock' => $stock,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edition", methods={"GET","POST"})
     */
    public function edition(Request $request, Stock $stock): Response
    {
        $form = $this->createForm(StockType::class, $stock);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('stockage');
        }

        return $this->render('stock/edition.html.twig', [
            'stock' => $stock,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="supprimer", methods={"DELETE"})
     */
    public function supprimer(Request $request, Stock $stock): Response
    {
        if ($this->isCsrfTokenValid('supprimer'.$stock->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($stock);
            $entityManager->flush();
        }

        return $this->redirectToRoute('stockage');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
              <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
              <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
              <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
              <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
               
            
<!------ Include the above in your HEAD tag ---------->

<link href="https://raw.githubusercontent.com/daneden/animate.css/master/animate.css" rel="stylesheet">

        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('css/style.css') }}">
        {% endblock %}
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <ul class="navbar-nav">
     <li class="nav-item">
        <a class="nav-link" href="{{ path('accueil') }}"> <b> ACCUEIL </b></a>
             </li>        
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('stockage') }}"> <b>STOCKS </b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('nouveau') }}"> <b>NOUVEAU STOCK </b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('information') }}"> <b>INFORMATIONS </b></a>
                </li>
            </ul>
        </div>
    </nav>
    

        {% block body %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        {% block javascripts %}
        
        
        {% endblock %}
    </body>
</html>

templates/index/accueil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Acceuil{% endblock %}

{% block body %}
    <div class="shake" style="
    text-align: center;
    /* font-size: 40%; */
    margin-top: 20%;">

    <a class="btn btn-secondary" href="/stock" style="
    /* text-align: center; */
    font-size: 55px;
    border-radius: 50% 20% / 10% 40%;
    "><b> GÉRER LES ÉQUIPEMENTS ! </b></a>
{% endblock %}

templates/info/information.html.twig
{% extends 'base.html.twig' %}

{% block title %}Information{% endblock %}

{% block body %}
<div class="container">
   <div class="row blog">
     <div class="col-md-12">
      <div id="blogCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#blogCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#blogCarousel" data-slide-to="1"></li>
            </ol>

                        <!-- Carousel items -->

          <h1 style="text-align: center;"> <b> DESCRIPTION DES PRODUITS </b> </h1> <br> <br>
            <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="row">
                    <div class="col-md-3">
                        <a href="#">
                            <img src="/img/412792.png/250x250" alt="Image" style="max-width:100%;">
                              <h1 style="color: black;text-align: center;">PLOT <br> (marionnaud)</h1>
                              <h4 style="color:black;"> 28€ </h4>
                            <p style="color: black;">Conçu pour le balisage de vos terrains de jeux et entraînements sportifs.</p>
                        </a>
                    </div>
                        <div class="col-md-3">
                            <a href="#">
                                <img src="/img/gilet-neon.jpg/250x250" alt="Image" style="max-width:100%;">
                            <h1 style="color: black;text-align: center;">CHASUBLE <br>(huit clos)</h1>
                            <p style="color: black;">Conçu pour le balisage de vos terrains de jeux et entraînements sportifs.</p>
                             <h4 style="color:black;"> 10€ </h4>
                            </a>
                        </div>
                        <div class="col-md-3">
                            <a href="#">
                                <img src="/img/—Pngtree—soccer wall crack_3553760.png/250x250" alt="Image" style="max-width:100%;">
                            <h1 style="color: black;text-align: center;">BALLON <br>(guicci)</h1>
                            <p style="color: black;">Conçu pour le balisage de vos terrains de jeux et entraînements sportifs.</p>
                             <h4 style="color:black;"> 40€ </h4>
                            </a>
                        </div>
                        <div class="col-md-3">
                            <a href="#">
                                <img src="/img/kisspng-tin-whistle-clip-art-whistle-5ac5e818064882.1628168915229194480257.jpg/250X250" alt="Image" style="max-width:100%;">
                            <h1 style="color: black;text-align: center;">SIFLET <br>(GO sport)</h1>
                            <p style="color: black;">Conçu pour le balisage de vos terrains de jeux et entraînements sportifs.</p>
                             <h4 style="color:black;"> 50€ </h4>
                            </a>
                        </div>
                    </div>
                    <!--.row-->
                </div>
                <!--.item-->
                <div class="carousel-item">
                    <div class="row">
                        <div class="col-md-3">
                            <a href="#">
                                <img src="/img/kisspng-adidas-shorts-kit-football-sport-short-5b1a2339246597.4021913715284396091491.jpg/250x250" alt="Image" style="max-width:100%;">
                            <h1 style="color: black;text-align: center;">MAILLOT <br>(Nike)</h1>
                            <p style="color: black;">Conçu pour le balisage de vos terrains de jeux et entraînements sportifs.</p>
                             <h4 style="color:black;"> 75€ </h4>
                            </a>
                        </div>
                        <div class="col-md-3">
                            <a href="#">
                                <img src="/img/—Pngtree—nba jerseys_2325689.png/250x250" alt="Image" style="max-width:100%;">
                            <h1 style="color: black;text-align: center;">SHORT <br>(Adidas)</h1>
                            <p style="color: black;">Conçu pour le balisage de vos terrains de jeux et entraînements sportifs.</p>
                             <h4 style="black:white;"> 222€ </h4>
                            </a>
                        </div>
                        <div class="col-md-3">
                            <a href="#">
                                <img src="/img/kisspng-plot-sports-training-horse-polyethylene-plot-5b22411b6b4446.4597000015289715474394.png/250x250" alt="Image" style="max-width:100%;">
                            <h1 style="color: black;text-align: center;">MINI PLOT BIZZARE <br>(Zara)</h1>
                            <p style="color: black;">Conçu pour le balisage de vos terrains de jeux et entraînements sportifs.</p>
                             <h4 style="color:black;"> 8€ </h4>
                            </a>
                        </div>
                        <div class="col-md-3">
                            <a href="#">
                                <img src="/img/6868101.png/250x250" alt="Image" style="max-width:100%;">
                            <h1 style="color: black;text-align: center;">BARRE <br>(LVMH)</h1>
                            <p style="color: black;">Conçu pour le balisage de vos terrains de jeux et entraînements sportifs.</p>
                             <h4 style="color:black;"> 5€ </h4>
                            </a>
                        </div>
                    </div>
                    <!--.row-->
                </div>
                <!--.item-->
            </div>
            <!--.carousel-inner-->
          </div>
          <!--.Carousel-->
          </div>
          </div>
          </div>

             
  
<!--slide end--> 

{% endblock %}

templates/stock/afficher.html.twig
{% extends 'base.html.twig' %}

{% block title %}Affichage de stock{% endblock %}

{% block body %}
    <div class="container container1">
        <h1> L'équipement qui reste en stock</h1>
        <h2><a class="btn btn-warning" href="{{ path('information') }}">INFORMATION SUPPLÉMENTAIRE</a></h2>

        <table class="table">
            <tbody>
                <tr>
                    <th>Stock numéro</th>
                    <td>{{ stock.id }}</td>
                </tr>
                <tr>
                    <th>Chasuble</th>
                    <td>{{ stock.chasuble }}</td>
                </tr>
                <tr>
                    <th>Ballon</th>
                    <td>{{ stock.ballon }}</td>
                </tr>
                <tr>
                    <th>Plot</th>
                    <td>{{ stock.plot }}</td>
                </tr>
                <tr>
                    <th>Barre</th>
                    <td>{{ stock.barre }}</td>
                </tr>
                <tr>
                    <th>Mini_plot</th>
                    <td>{{ stock.miniPlot }}</td>
                </tr>
                <tr>
                    <th>Maillot</th>
                    <td>{{ stock.maillot }}</td>
                </tr>
                <tr>
                    <th>Short</th>
                    <td>{{ stock.short }}</td>
                </tr>
                <tr>
                    <th>Sifflet</th>
                    <td>{{ stock.sifflet }}</td>
                </tr>
            </tbody>
        </table>

        <div style="display: inline-block"><a class="btn btn-primary" href="{{ path('stockage') }}">Retour à la liste</a></div>
        <div style="display: inline-block"><a class="btn btn-success" href="{{ path('edition', {'id': stock.id}) }}">Modifier</a></div>
        <div style="display: inline-block">{{ include('stock/supprimer.html.twig') }}</div>
    </div>
{% endblock %}

templates/stock/edition.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Stock{% endblock %}

{% block body %}
    <div class="container container2">
        <h1>Modifier le stock</h1>

        <div style="display: block">{{ include('stock/form.html.twig', {'button_label': 'Modifier'}) }}</div>
        <div style="display: inline-block"> <br><a class="btn btn-primary" href="{{ path('stockage') }}">Retour à la liste</a></div>
        <div style="display: inline-block">{{ include('stock/supprimer.html.twig') }}</div>

    </div>
{% endblock %}

templates/stock/form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/stock/nouveau.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Stock{% endblock %}

{% block body %}
    <div class="container container2">
    <div class="table-responsive text-nowrap">
    <h1> Créer ton nouveau stock </h1>

         <div style="table">{{ include('stock/form.html.twig') }} <br>
         <div style="display: inline-block"><a class="btn btn-secondary" href="{{ path('stockage') }}">Retour à la liste</a>


</div>
    
    </div>
{% endblock %}

templates/stock/stockage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stockage{% endblock %}

{% block body %}
    <div class="container container2">
        <h1> Stocks des équipements</h1>

        <table class="table">
  <thead class="thead-dark">
  {% for stock in stocks %}
    <tr>
      <th scope="col">1</th>
      <th scope="col">Equipement</th>
      <th scope="col">Nombre</th>
      <th scope="col">Stockage</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">2</th>
      <td>Chasuble</td>
        <td>{{ stock.chasuble }}</td>
        <td>{{ stock.id }}</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Ballon</td>
      <td>{{ stock.ballon }}</td>
    </tr>
    <tr>
      <th scope="row">4</th>
      <td>Plot</td>
      <td>{{ stock.plot }}</td>
    </tr>
    <tr>
      <th scope="col">5</th>
      <td>Barre</td>
      <td>{{ stock.barre }}</td>
    </tr>
    <tr>
      <th scope="row">6</th>
      <td>Mini_plot</td>
      <td>{{ stock.miniPlot }}</td>
    </tr>
    <tr>
      <th scope="row">7</th>
      <td>Maillot</td>
      <td>{{ stock.maillot }}</td>
    </tr>
    <tr>
      <th scope="row">8</th>
      <td>Short</td>
      <td>{{ stock.short }}</td>
    </tr>
    <tr>
      <th scope="row">9</th>
      <td>Sifflet</td>
      <td>{{ stock.sifflet }}</td>
    </tr>
  </tbody>

  
</table>
        <table class="table">
            <thead>        
              <th>actions</th>
                    <td>
                        <a class="btn btn-danger" href="{{ path('afficher', {'id': stock.id}) }}">Afficher</a>
                        <a class="btn btn-secondary" href="{{ path('edition', {'id': stock.id}) }}">Modifier</a>
                        <a class="btn btn-success" href="{{ path('nouveau') }}">Nouvelle commande de stock</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan>Aucune page trouvée,</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/stock/supprimer.html.twig
<form method="post" action="{{ path('supprimer', {'id': stock.id}) }}" onsubmit="return confirm('Etes vous réellement sur de vouloir supprimer ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('supprimer' ~ stock.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>